"""Download the human-labeled calibration set.

HarmBench's classifier validation set ships with three human votes per item and
is directly downloadable. This is the concretely-runnable calibration source
(StrongREJECT's LabelBox CSV is generated by their replication scripts).
"""

from __future__ import annotations

import urllib.request
from pathlib import Path

HARMBENCH_VAL_URL = (
    "https://raw.githubusercontent.com/centerforaisafety/HarmBench/main/"
    "data/classifier_val_sets/text_behaviors_val_set.json"
)


def fetch_harmbench_val(dest: str | Path) -> Path:
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    urllib.request.urlretrieve(HARMBENCH_VAL_URL, dest)  # noqa: S310 - fixed https url
    return dest
